var quotes = {
	"0": "The question isn't who is going to let me; it's who is going to stop me.",
	"1": "Learn to value yourself, which means: fight for your happiness.",
	"2": "I could die for you. But I couldn't, and wouldn't, live for you.",
	"3": "Freedom (n.): To ask nothing. To expect nothing. To depend on nothing.",
	"4": "A creative man is motivated by the desire to achieve, not by the desire to beat others.",
	"5": "To say \"I love you\" one must know first how to say the \"I\".",
	"6": "I swear by my life and my love of it that I will never live for the sake of another man, nor ask another man to live for mine.",
	"7": "If you don't know, the thing to do is not to get scared, but to learn.",
	"8": "The hardest thing to explain is the glaringly evident which everybody has decided not to see.",
	"9": "The man who does not value himself, cannot value anything or anyone.",
	"10": "You can avoid reality, but you cannot avoid the consequences of avoiding reality.",
	"11": "The truth is not for all men but only for those who seek it.",
	"12": "Contradictions do not exist. Whenever you think that you are facing a contradiction, check your premises. You will find that one of them is wrong.",
	"13": "My happiness is not the means to any end. It is the end. It is its own goal. It is its own purpose.",
	"14": "Never think of pain or danger or enemies a moment longer than is necessary to fight them.",
	"15": "Don't fool yourself, my dear. You're much worse than a bitch. You're a saint. Which shows why saints are dangerous and undesirable.",
	"16": "Let me give you a tip on a clue to men's characters: the man who damns money has obtained it dishonorably; the man who respects it has earned it.",
	"17": "If it's worth doing, it's worth overdoing.",
	"18": "She did not know the nature of her loneliness. The only words that named it were: This is not the world I expected.",
	"19": "There are two sides to every issue: one side is right and the other is wrong, but the middle is always evil.",
	"20": "You have been the one encounter in my life that can never be repeated",
	"21": "A government is the most dangerous threat to man's rights: it holds a legal monopoly on the use of physical force against legally disarmed victims.",
	"22": "Who is John Galt?",
	"23": "The purpose of morality is to teach you, not to suffer and die, but to enjoy yourself and live.",
	"24": "I never found beauty in longing for the impossible and never found the possible to be beyond my reach.",
	"25": "I worship individuals for their highest possibilities as individuals and I loathe humanity for its failure to live up to these possibilities.",
	"26": "To sell your soul is the easiest thing in the world. That's what everybody does every hour of his life.",
	"27": "I never found beauty in longing for the impossible and never found the possible to be beyond my reach.",
	"28": "I worship individuals for their highest possibilities as individuals and I loathe humanity for its failure to live up to these possibilities.",
	"29": "I think, therefore I'll think.",
	"30": "But why should you care what people will say? All you have to do is please yourself.",
	"31": "People create their own questions because they are afraid to look straight. All you have to do is look straight and see the road, and when you see it, don't sit looking at it - walk.",
	"32": "What greater wealth is there than to own your life and to spend it on growing? Every living thing must grow. It can't stand still. It must grow or perish.",
	"33": "When I disagree with a rational man, I let reality be our final arbiter; if I am right, he will learn; if I am wrong, I will; one of us will win, but both will profit.",
	"34": "Run for your life from any man who tells you that money is evil. That sentence is the leper's bell of an approaching looter.",
	"35": "Live and act within the limit of your knowledge and keep expanding it to the limit of your life.",
	"36": "Patience is always rewarded and romance is always round the corner!",
	"37": "There is no such thing as a lousy job - only lousy men who don't care to do it.",
	"38": "Joy is the goal of existence, and joy is not to be stumbled upon, but to be achieved, and the act of treason is to let its vision drown in the swamp of the moment's torture.",
	"39": "Rationalization is a process of not perceiving reality, but of attempting to make reality fit one's emotions.",
	"40": "If one's actions are honest, one does not need the predated confidence of others.",
	"41": "Have you ever felt the longing for someone you could admire? For something, not to look down at, but up to?",
	"42": "She knew that even pain can be confessed, but to confess happiness is to stand naked, delivered to the witness...",
	"43": "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.",
	"44": "What is man? He's just a collection of chemicals with delusions of grandeur.",
	"45": "I can accept anything, except what seems to be the easiest for most people: the half-way, the almost, the just-about, the in-between.",
	"46": "It is not death that we wish to avoid, but life that we wish to live.",
	"47": "Self respect is something that can't be killed. The worst thing is to kill a man's pretense at it.",
	"48": "In this world, either you're virtuous or you enjoy yourself. Not both, lady, not both.",
	"49": "Men who reject the responsibility of thought and reason can only exist as parasites on the thinking of others.",
	"50": "Self-sacrifice? But it is precisely the self that cannot and must not be sacrificed.",
	"51": "He liked to observe emotions; they were like red lanterns strung along the dark unknown of another's personality, marking vulnerable points.",
	"52": "Within the extent of your knowledge, you are right.",
	"53": "Reason is not automatic. Those who deny it cannot be conquered by it. Do not count on them. Leave them alone.",
	"54": "The most depraved type of human being ... (is) the man without a purpose.",


};